export const FETCH_SITES_BEGIN = 'FETCH_SITES_BEGIN';
export const FETCH_SITES_SUCCESS = 'FETCH_SITES_SUCCESS';
export const FETCH_SITES_FAILURE = 'FETCH_SITES_FAILURE';
export const POLLUTANT_SELECT = 'POLLUTANT_SELECT';
export const REGION_CLICK = 'REGION_CLICK';
export const ENVIRON_CLICK = 'ENVIRON_CLICK';
